# Setup the environment:
dist: xenial

before_script:
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc++-dev

matrix:
  include:
    - compiler: clang
    - compiler: gcc
      env: TARGETS="compiler-gcc"

install:
  - gem install teapot

# Run tests:
script:
  - teapot fetch
  - teapot build Test/AsyncNetwork $TARGETS
